
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userclouds-authz
  labels:
    app.kubernetes.io/component: authz
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: authz
      {{- include "userclouds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: authz
        {{- include "userclouds.labels" . | nindent 8 }}
    spec:
      {{- if .Values.userclouds.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.userclouds.nodeSelector | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: configmap
          configMap:
            name: userclouds-configs
            items:
              - key: base
                path: base_onprem.yaml
              - key: authz
                path: authz/onprem.yaml
      containers:
        - name: authz
          image: "{{ .Values.image.repository_base }}/service/authz:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- include "userclouds.envVars" . | nindent 10 }}
          resources:
            {{- toYaml .Values.authz.resources | nindent 12 }}
          volumeMounts:
            - name: configmap
              mountPath: /userclouds/configmaps
          ports:
            - name: authz
              containerPort: 5000
              protocol: TCP
            - name: internal
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /healthcheck
              port: authz
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: authz

---
apiVersion: v1
kind: Service
metadata:
  name: userclouds-authz
  labels:
    app.kubernetes.io/component: authz
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: authz
    {{- include "userclouds.selectorLabels" . | nindent 4 }}
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: internal
      protocol: TCP
      port: 5001

