
apiVersion: v1
kind: ConfigMap
metadata:
  name: userclouds-configs
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
data:
  rootdb_onprem: |
     db:
      user: {{ .Values.config.db.user }}
      password: env://PG_PASSWORD
      dbname: defaultdb
      host: {{ .Values.config.db.host }}
      dbdriver: postgres
      dbproduct: aws-rds-postgres
      port: {{ .Values.config.db.port }}
  base_onprem: |
    company_db:
      user: {{ .Values.config.db.user }}
      password: env://PG_PASSWORD
      dbname: companyconfig
      host: {{ .Values.config.db.host }}
      dbdriver: postgres
      dbproduct: aws-rds-postgres
      port: {{ .Values.config.db.port }}
    logger:
      transports:
        - type: goLogJSON
          transportconfig:
            required: true
            max_log_level: 5
        - type: server
          transportconfig:
            required: true
            max_log_level: 5
          tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a
          log_service_url: 'http://userclouds-logserver.{{ .Release.Namespace }}.svc.cluster.local'
          send_raw_data: false
    cache:
      redis_caches:
        - region: customerlocal
          host: userclouds-redis.{{ .Release.Namespace }}.svc.cluster.local
          port: 6379
          dbname: 0
  rootdbstatus_onprem: |
     db:
      user: {{ .Values.config.db.user }}
      password: env://PG_PASSWORD
      dbname: rootdbstatus
      host: {{ .Values.config.db.host }}
      dbdriver: postgres
      dbproduct: aws-rds-postgres
      port: {{ .Values.config.db.port }}
  logdb_onprem: |
    db:
      user: {{ .Values.config.db.user }}
      password: env://PG_PASSWORD
      dbname: status_00000000000000000000000000000000
      host: {{ .Values.config.db.host }}
      dbdriver: postgres
      dbproduct: aws-rds-postgres
      port: {{ .Values.config.db.port }}
  logserver_base: |
     db:
      user: {{ .Values.config.db.user }}
      password: env://PG_PASSWORD
      dbname: status_00000000000000000000000000000000
      host: {{ .Values.config.db.host }}
      dbdriver: postgres
      dbproduct: aws-rds-postgres
      port: {{ .Values.config.db.port }}
  console_base: |
     tenant_sub_domain: tenant.{{ .Values.config.customerDomain }}
     tenant_protocol: https
     console_service_url: https://console.{{ .Values.config.customerDomain }}
     log_db:
      user: {{ .Values.config.db.user }}
      password: {{ .Values.config.db.password }}
      dbname: status_00000000000000000000000000000000
      host: {{ .Values.config.db.host }}
      dbdriver: postgres
      dbproduct: aws-rds-postgres
      port: {{ .Values.config.db.port }}
  idp_onprem: |
    internal_server:
        protocol: http
        host: 0.0.0.0
        port: 5101
    svc_listener:
        protocol: http
        host: 0.0.0.0
        port: 5100
    console_tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a
    sqlshim_config:
      mysql_ports: [3306, 3307, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315]
      health_check_port: {{ .Values.dbproxy.mysql.healthCheckPort }}
  worker_base: |
    log_db:
      user: {{ .Values.config.db.user }}
      password: env://PG_PASSWORD
      dbname: status_00000000000000000000000000000000
      host: {{ .Values.config.db.host }}
      dbdriver: postgres
      dbproduct: aws-rds-postgres
      port: {{ .Values.config.db.port }}

