{{- if .Values.console.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userclouds-on-prem-console
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: userclouds-on-prem-console
    alb.ingress.kubernetes.io/scheme: {{ .Values.console.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: "/healthcheck"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    {{- if .Values.console.ingress.additionalAnnotations }}
    {{ toYaml  .Values.console.ingress.additionalAnnotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: alb
  rules:
  - host: console.{{ .Values.config.customerDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: userclouds-console
            port:
              number: 80
{{- end }}
