apiVersion: apps/v1
kind: Deployment
metadata:
  name: userclouds-redis
  labels:
    app.kubernetes.io/component: redis
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      {{- include "userclouds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        {{- include "userclouds.labels" . | nindent 8 }}
    spec:
      {{- if .Values.redis.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.redis.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: public.ecr.aws/docker/library/redis:7.4.2-alpine
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: userclouds-redis
  labels:
    app.kubernetes.io/component: redis
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: redis
    {{- include "userclouds.labels" . | nindent 4 }}
  ports:
    - name: redis
      protocol: TCP
      port: 6379
