
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userclouds-worker
  labels:
    app.kubernetes.io/component: worker
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
     {{- include "userclouds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        {{- include "userclouds.labels" . | nindent 8 }}
    spec:
      {{- if .Values.userclouds.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.userclouds.nodeSelector | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: configmap
          configMap:
            name: userclouds-configs
            items:
              - key: base_onprem
                path: base_onprem.yaml
              - key: worker_base
                path: worker/base.yaml
      containers:
        - name: worker
          image: "{{ .Values.image.repository_base }}/service/worker:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- include "userclouds.envVars" . | nindent 10 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: configmap
              mountPath: /userclouds/configmaps
          ports:
            - name: worker
              containerPort: 5000
              protocol: TCP
            - name: internal
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: worker
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: worker

---
apiVersion: v1
kind: Service
metadata:
  name: userclouds-worker
  labels:
    app.kubernetes.io/component: worker
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: worker
    {{- include "userclouds.selectorLabels" . | nindent 4 }}
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: internal
      protocol: TCP
      port: 5001

